const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

const APP_NAME = 'CityConnect Backend';

const OTP_EXPIRY_MINUTES = 10;
const OTP_MAX_ATTEMPTS = 3;
const OTP_ATTEMPT_WINDOW_MINUTES = 5;
const USER_MAX_ADDRESSES = 5;
const CART_MAX_ITEMS = 50;
const CART_EXPIRY_DAYS = 30;
const CART_TAX_RATE = 0.05;
const CART_OFFER_MAX_DISCOUNT_PERCENT = 30;
const CART_COUPON_MAX_DISCOUNT_PERCENT = 50;
const FREE_DELIVERY_MIN_ORDER = 999;
const USER_MIN_ORDER_VALUE = 100;
const OFFER_PERCENT_MAX_OF_ORDER = 80;
const MAX_OFFERS_PER_SHOP = 50;

const ORDER_PAYMENT_MODES = {
  COD: 'COD',
  ONLINE: 'ONLINE',
};

const ORDER_PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const ORDER_STATUS = {
  NEW: 'NEW',
  ACCEPTED: 'ACCEPTED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

const SHOPKEEPER_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DISABLED: 'DISABLED',
};

const SHOP_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
};

const AUDIT_EVENT_TYPES = {
  GENERIC_EVENT: 'GENERIC_EVENT',
  CONFIG_UPDATED: 'CONFIG_UPDATED',
  CONFIG_RESET: 'CONFIG_RESET',
  CITY_CREATED: 'CITY_CREATED',
  CITY_UPDATED: 'CITY_UPDATED',
  CITY_TOGGLED_ACTIVE: 'CITY_TOGGLED_ACTIVE',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_PUBLISHED: 'CATEGORY_PUBLISHED',
  SHOP_APPROVED: 'SHOP_APPROVED',
  SHOP_REJECTED: 'SHOP_REJECTED',
  SHOP_SUSPENDED: 'SHOP_SUSPENDED',
  SHOP_UPDATED: 'SHOP_UPDATED',
  ORDER_FORCE_CANCELLED: 'ORDER_FORCE_CANCELLED',
  ORDER_REFUND_TRIGGERED: 'ORDER_REFUND_TRIGGERED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  PAYMENT_VERIFY_RETRIED: 'PAYMENT_VERIFY_RETRIED',
  PAYMENT_UPDATED: 'PAYMENT_UPDATED',
  PAYOUT_APPROVED: 'PAYOUT_APPROVED',
  PAYOUT_COMPLETED: 'PAYOUT_COMPLETED',
  COMMISSION_UPDATED: 'COMMISSION_UPDATED',
  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  SUBSCRIPTION_PLAN_UPDATED: 'SUBSCRIPTION_PLAN_UPDATED',
  REFUND_UPDATED: 'REFUND_UPDATED',
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
};

const ACCESS_TOKEN_EXPIRY = '1d';
const REFRESH_TOKEN_EXPIRY = '30d';

const AUTH_ACTOR_TYPES = {
  USER: 'user',
  SHOPKEEPER: 'shopkeeper',
  ADMIN: 'admin',
};

const ACCESS_TOKEN_EXPIRY_BY_TYPE = {
  [AUTH_ACTOR_TYPES.USER]: '7d',
  [AUTH_ACTOR_TYPES.SHOPKEEPER]: '7d',
  [AUTH_ACTOR_TYPES.ADMIN]: '24h',
};

const REFRESH_TOKEN_EXPIRY_BY_TYPE = {
  [AUTH_ACTOR_TYPES.USER]: '30d',
  [AUTH_ACTOR_TYPES.SHOPKEEPER]: '30d',
  [AUTH_ACTOR_TYPES.ADMIN]: '30d',
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPT_LIMIT_REACHED: 'OTP_ATTEMPT_LIMIT_REACHED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  SHOP_NOT_FOUND: 'SHOP_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_MAX_ITEMS_REACHED: 'CART_MAX_ITEMS_REACHED',
  CART_QUANTITY_EXCEEDS_STOCK: 'CART_QUANTITY_EXCEEDS_STOCK',
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_MIN_ORDER_NOT_MET: 'COUPON_MIN_ORDER_NOT_MET',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_FEEDBACK_NOT_ALLOWED: 'ORDER_FEEDBACK_NOT_ALLOWED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
  INVENTORY_LOCK_FAILED: 'INVENTORY_LOCK_FAILED',
  INVENTORY_RELEASE_FAILED: 'INVENTORY_RELEASE_FAILED',
  INVENTORY_DEDUCT_FAILED: 'INVENTORY_DEDUCT_FAILED',
  MIN_ORDER_VALUE_NOT_MET: 'MIN_ORDER_VALUE_NOT_MET',
  ADDRESS_OUTSIDE_SERVICE_AREA: 'ADDRESS_OUTSIDE_SERVICE_AREA',
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_EDIT_WINDOW_EXPIRED: 'REVIEW_EDIT_WINDOW_EXPIRED',
  REVIEW_DELETE_WINDOW_EXPIRED: 'REVIEW_DELETE_WINDOW_EXPIRED',
  REVIEW_ORDER_NOT_ELIGIBLE: 'REVIEW_ORDER_NOT_ELIGIBLE',
  SHOPKEEPER_NOT_FOUND: 'SHOPKEEPER_NOT_FOUND',
  SHOPKEEPER_ALREADY_EXISTS: 'SHOPKEEPER_ALREADY_EXISTS',
  SHOPKEEPER_SUSPENDED: 'SHOPKEEPER_SUSPENDED',
  SHOPKEEPER_DISABLED: 'SHOPKEEPER_DISABLED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SHOP_OWNER_MISMATCH: 'SHOP_OWNER_MISMATCH',
  BANK_DETAILS_INVALID: 'BANK_DETAILS_INVALID',
  LOGIN_RATE_LIMITED: 'LOGIN_RATE_LIMITED',
  SHOP_NOT_APPROVED: 'SHOP_NOT_APPROVED',
  SHOP_CITY_IMMUTABLE: 'SHOP_CITY_IMMUTABLE',
  SHOP_SLUG_TAKEN: 'SHOP_SLUG_TAKEN',
  PRODUCT_IN_RECENT_ORDERS: 'PRODUCT_IN_RECENT_ORDERS',
  OFFER_NOT_FOUND: 'OFFER_NOT_FOUND',
  OFFER_SCOPE_INVALID: 'OFFER_SCOPE_INVALID',
  OFFER_LIMIT_EXCEEDED: 'OFFER_LIMIT_EXCEEDED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  MAX_ADDRESSES_REACHED: 'MAX_ADDRESSES_REACHED',
  LAST_ADDRESS_DELETE_BLOCKED: 'LAST_ADDRESS_DELETE_BLOCKED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  MISSING_TOKEN: 'MISSING_TOKEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  REFERRAL_CODE_GENERATION_FAILED: 'REFERRAL_CODE_GENERATION_FAILED',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  INVENTORY_ERROR: 'INVENTORY_ERROR',
  OTP_ERROR: 'OTP_ERROR',
  UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',
  FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
};

module.exports = {
  HTTP_STATUS,
  APP_NAME,
  OTP_EXPIRY_MINUTES,
  OTP_MAX_ATTEMPTS,
  OTP_ATTEMPT_WINDOW_MINUTES,
  USER_MAX_ADDRESSES,
  CART_MAX_ITEMS,
  CART_EXPIRY_DAYS,
  CART_TAX_RATE,
  CART_OFFER_MAX_DISCOUNT_PERCENT,
  CART_COUPON_MAX_DISCOUNT_PERCENT,
  FREE_DELIVERY_MIN_ORDER,
  USER_MIN_ORDER_VALUE,
  OFFER_PERCENT_MAX_OF_ORDER,
  MAX_OFFERS_PER_SHOP,
  ORDER_PAYMENT_MODES,
  ORDER_PAYMENT_STATUS,
  ORDER_STATUS,
  SHOPKEEPER_STATUS,
  SHOP_STATUS,
  AUDIT_EVENT_TYPES,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  AUTH_ACTOR_TYPES,
  ACCESS_TOKEN_EXPIRY_BY_TYPE,
  REFRESH_TOKEN_EXPIRY_BY_TYPE,
  ERROR_CODES,
};
