const express = require('express');
const { healthController } = require('../controllers/healthController');
const authRoutes = require('./authRoutes');
const usersRoutes = require('./usersRoutes');
const citiesRoutes = require('./citiesRoutes');
const shopsRoutes = require('./shopsRoutes');
const productsRoutes = require('./productsRoutes');
const categoriesRoutes = require('./categoriesRoutes');
const cartRoutes = require('./cartRoutes');
const ordersRoutes = require('./ordersRoutes');
const paymentsRoutes = require('./paymentsRoutes');
const reviewsRoutes = require('./reviewsRoutes');
const shopkeeperRoutes = require('./shopkeeperRoutes');
const shopkeeperPaymentsRoutes = require('./shopkeeperPaymentsRoutes');
const offersRoutes = require('./offersRoutes');
const couponsRoutes = require('./couponsRoutes');
const adminCitiesRoutes = require('./adminCitiesRoutes');
const adminCategoriesRoutes = require('./adminCategoriesRoutes');
const adminShopsRoutes = require('./adminShopsRoutes');
const adminCouponsRoutes = require('./adminCouponsRoutes');
const adminPaymentsRoutes = require('./adminPaymentsRoutes');
const adminCommissionRoutes = require('./adminCommissionRoutes');
const adminPayoutsRoutes = require('./adminPayoutsRoutes');
const adminOrdersRoutes = require('./adminOrdersRoutes');
const adminRefundsRoutes = require('./adminRefundsRoutes');
const adminSubscriptionPlansRoutes = require('./adminSubscriptionPlansRoutes');
const adminSubscriptionsRoutes = require('./adminSubscriptionsRoutes');
const adminAuditLogsRoutes = require('./adminAuditLogsRoutes');
const adminConfigRoutes = require('./adminConfigRoutes');

const router = express.Router();

router.get('/health', healthController);
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/cities', citiesRoutes);
router.use('/shops', shopsRoutes);
router.use('/products', productsRoutes);
router.use('/categories', categoriesRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', ordersRoutes);
router.use('/payments', paymentsRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/shopkeeper', shopkeeperRoutes);
router.use('/shopkeeper', shopkeeperPaymentsRoutes);
router.use('/offers', offersRoutes);
router.use('/coupons', couponsRoutes);
router.use('/admin/cities', adminCitiesRoutes);
router.use('/admin/categories', adminCategoriesRoutes);
router.use('/admin/shops', adminShopsRoutes);
router.use('/admin/coupons', adminCouponsRoutes);
router.use('/admin/payments', adminPaymentsRoutes);
router.use('/admin/commission', adminCommissionRoutes);
router.use('/admin/payouts', adminPayoutsRoutes);
router.use('/admin/orders', adminOrdersRoutes);
router.use('/admin/refunds', adminRefundsRoutes);
router.use('/admin/subscription-plans', adminSubscriptionPlansRoutes);
router.use('/admin/subscriptions', adminSubscriptionsRoutes);
router.use('/admin/audit-logs', adminAuditLogsRoutes);
router.use('/admin/config', adminConfigRoutes);

module.exports = router;
