export const SYSTEM_RESET = 'SYSTEM_RESET'

export const CITY_CREATED = 'CITY_CREATED'
export const CITY_UPDATED = 'CITY_UPDATED'
export const CITY_TOGGLED_ACTIVE = 'CITY_TOGGLED_ACTIVE'
export const CITY_TOGGLED_DELIVERY = 'CITY_TOGGLED_DELIVERY'

export const CATEGORY_CREATED = 'CATEGORY_CREATED'
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED'
export const CATEGORY_TOGGLED_ACTIVE = 'CATEGORY_TOGGLED_ACTIVE'
export const CATEGORY_PUBLISHED = 'CATEGORY_PUBLISHED'

export const SUBCATEGORY_ADDED = 'SUBCATEGORY_ADDED'
export const SUBCATEGORY_REMOVED = 'SUBCATEGORY_REMOVED'

export const SHOP_APPROVED = 'SHOP_APPROVED'
export const SHOP_REJECTED = 'SHOP_REJECTED'
export const SHOP_SUSPENDED = 'SHOP_SUSPENDED'
export const SHOP_REACTIVATED = 'SHOP_REACTIVATED'
export const SHOP_PUBLIC_TOGGLED = 'SHOP_PUBLIC_TOGGLED'
export const SHOP_SLUG_UPDATED = 'SHOP_SLUG_UPDATED'

export const ORDER_FORCE_CANCELLED = 'ORDER_FORCE_CANCELLED'
export const ORDER_REFUND_TRIGGERED = 'ORDER_REFUND_TRIGGERED'

export const CONFIG_UPDATED = 'CONFIG_UPDATED'
export const FEATURE_FLAG_TOGGLED = 'FEATURE_FLAG_TOGGLED'

export const COMMISSION_DEFAULT_UPDATED = 'COMMISSION_DEFAULT_UPDATED'
export const COMMISSION_OVERRIDE_UPSERTED = 'COMMISSION_OVERRIDE_UPSERTED'
export const COMMISSION_OVERRIDE_REMOVED = 'COMMISSION_OVERRIDE_REMOVED'

export const PAYMENT_VERIFY_RETRIED = 'PAYMENT_VERIFY_RETRIED'

export const PAYOUT_APPROVED = 'PAYOUT_APPROVED'
export const PAYOUT_REJECTED = 'PAYOUT_REJECTED'
export const PAYOUT_COMPLETED = 'PAYOUT_COMPLETED'

export const REFUND_CREATED = 'REFUND_CREATED'
export const REFUND_PROCESSING = 'REFUND_PROCESSING'
export const REFUND_COMPLETED = 'REFUND_COMPLETED'
export const REFUND_FAILED = 'REFUND_FAILED'

export const COUPON_CREATED = 'COUPON_CREATED'
export const COUPON_UPDATED = 'COUPON_UPDATED'
export const COUPON_TOGGLED_ACTIVE = 'COUPON_TOGGLED_ACTIVE'

export const PLAN_UPDATED = 'PLAN_UPDATED'
export const PLAN_TOGGLED_ACTIVE = 'PLAN_TOGGLED_ACTIVE'

export const AUDIT_EVENT_TYPES = {
  SYSTEM_RESET,
  CITY_CREATED,
  CITY_UPDATED,
  CITY_TOGGLED_ACTIVE,
  CITY_TOGGLED_DELIVERY,
  CATEGORY_CREATED,
  CATEGORY_UPDATED,
  CATEGORY_TOGGLED_ACTIVE,
  CATEGORY_PUBLISHED,
  SUBCATEGORY_ADDED,
  SUBCATEGORY_REMOVED,
  SHOP_APPROVED,
  SHOP_REJECTED,
  SHOP_SUSPENDED,
  SHOP_REACTIVATED,
  SHOP_PUBLIC_TOGGLED,
  SHOP_SLUG_UPDATED,
  ORDER_FORCE_CANCELLED,
  ORDER_REFUND_TRIGGERED,
  CONFIG_UPDATED,
  FEATURE_FLAG_TOGGLED,
  COMMISSION_DEFAULT_UPDATED,
  COMMISSION_OVERRIDE_UPSERTED,
  COMMISSION_OVERRIDE_REMOVED,
  PAYMENT_VERIFY_RETRIED,
  PAYOUT_APPROVED,
  PAYOUT_REJECTED,
  PAYOUT_COMPLETED,
  REFUND_CREATED,
  REFUND_PROCESSING,
  REFUND_COMPLETED,
  REFUND_FAILED,
  COUPON_CREATED,
  COUPON_UPDATED,
  COUPON_TOGGLED_ACTIVE,
  PLAN_UPDATED,
  PLAN_TOGGLED_ACTIVE,
} as const

export type StandardAuditEventType = (typeof AUDIT_EVENT_TYPES)[keyof typeof AUDIT_EVENT_TYPES]
